# Coursework 3 - Coding Theory

### PLAGIARISM/COLLUSION DECLARATION

Coursework submitted for assessment must be the original work of you and your group. Assignments are subjected to regular checks for plagiarism and/or collusion. Plagiarism is the presentation of another person’s thoughts or words (those outside your group) as if they were your own. Collusion involves obtaining help from someone outside your group to complete your work. In preparing your coursework, you should not seek help, or copy from any other person or source, including the
Internet, without proper and explicit acknowledgement.

There is a procedure in place for you to declare individual contributions within your group for courswork. You must declare the contributions fairly and accurately.

You must not disclose your solutions or insights related to coursework with anyone else, including future students or the Internet.

By acknowledging the the statements above, you are declaring that both this and all subsequent pieces of coursework are, and will remain, the original work of you and your group. 

* Submissions will not be accepted without the aforementioned declaration.

* Members of a group are deemed to have collective responsibility for the integrity for work submitted and are liable for any penalty imposed, proportionate to their contributions. 



In [97]:
using FileIO, JLD2, LinearAlgebra, Nemo

In [98]:
Base.@kwdef mutable struct CourseWork_3
    CID::Int
    Plagiarism_declare::Union{Missing,Bool}
    Demo_willing::Union{Missing,Bool}

    "Q9.1"
    Q9_1_a_ans_G :: Union{Missing, Matrix{Int64}}

    Q9_1_b_data_p :: Float64
    Q9_1_b_ans_p_err :: Union{Missing, Float64}

    Q9_1_c_data_y_1 :: Vector{Int64}
    Q9_1_c_ans_i :: Union{Missing, Vector{Int64}}
    Q9_1_c_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_1_c_ans_iii :: Union{Missing, Vector{Int64}}

    Q9_1_d_data_y_2 :: Vector{Any}
    Q9_1_d_ans_i :: Union{Missing, Vector{Int64}}
    Q9_1_d_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_1_d_ans_iii :: Union{Missing, Vector{Int64}}

    "Q9.2"
    Q9_2_data_r :: Int64
    Q9_2_data_q :: Int64

    Q9_2_a_ans_H :: Union{Missing, Matrix{Int64}}

    Q9_2_b_ans_n :: Union{Missing, Int64}
    Q9_2_b_ans_k :: Union{Missing, Int64}
    Q9_2_b_ans_d :: Union{Missing, Int64}

    Q9_2_c_ans_is_perfect_code :: Union{Missing,Bool}

    Q9_2_d_ans_G :: Union{Missing, Matrix{Int64}}

    Q9_2_e_data_y_1 :: Vector{Int64}
    Q9_2_e_ans_i :: Union{Missing, Vector{Int64}}
    Q9_2_e_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_2_e_ans_iii :: Union{Missing, Vector{Int64}}

    Q9_2_f_data_y_2 :: Vector{Any}
    Q9_2_f_ans_i :: Union{Missing, Vector{Int64}}
    Q9_2_f_ans_ii :: Union{Missing, Vector{Int64}}
    Q9_2_f_ans_iii :: Union{Missing, Vector{Int64}}
    
    "Q9.3"
    Q9_3_data_n::Int
    Q9_3_data_k1::Int
    Q9_3_data_k2::Int
    Q9_3_data_p::Int
    Q9_3_a_ans_alpha::Union{Missing, Int}
    Q9_3_b_ans_generator::Union{Missing, Matrix{Int}}
    Q9_3_b_ans_parity::Union{Missing, Matrix{Int}}
    Q9_3_c_ans_generator::Union{Missing, Matrix{Int}}
    Q9_3_c_ans_parity::Union{Missing, Matrix{Int}}
    Q9_3_d_ans_generator::Union{Missing, Matrix{Int}}
    Q9_3_d_ans_parity::Union{Missing, Matrix{Int}}
    Q9_3_e_ans_generator::Union{Missing, Matrix{Int}}
    Q9_3_e_ans_parity::Union{Missing, Matrix{Int}}
    Q9_3_f_ans_generator::Union{Missing, Matrix{Int}}
    Q9_3_f_ans_parity::Union{Missing, Matrix{Int}}
    Q9_3_g_ans_generator::Union{Missing, Matrix{Int}}
    Q9_3_g_ans_parity::Union{Missing, Matrix{Int}}

    "Chapter 10"
    Q10_data_polynomial::Vector{Int64}
    Q10_data_primitive_el::Vector{Int64}
    Q10_1_ans_G::Union{Missing, Matrix{Vector{Int64}}}
    Q10_1_ans_H::Union{Missing, Matrix{Vector{Int64}}}
    Q10_2_data_y::Matrix{Vector{Int64}}
    Q10_2_ans_syndrome_vector::Union{Missing, Matrix{Vector{Int64}}}
    Q10_2_ans_syndrome_poly::Union{Missing, Matrix{Vector{Int64}}}
    Q10_3_ans_error_locator_poly::Union{Missing, Matrix{Vector{Int64}}}
    Q10_3_ans_error_evaluator_poly::Union{Missing, Matrix{Vector{Int64}}}
    Q10_4_ans_error_vector::Union{Missing, Matrix{Vector{Int64}}}
    Q10_5_ans_message::Union{Missing, Matrix{Vector{Int64}}}
    Q10_6_ans_n::Union{Missing, Int}

end

CourseWork_3

In [126]:
data = JLD2.load("Jacky Jiang1860908StudentFile.jld2")
CW3_DATA = data["CourseWork_3"]

CW3_DATA.CID = 01860908
CW3_DATA.Plagiarism_declare = true
CW3_DATA.Demo_willing = true

true

### 9.1

In [100]:
H = [1 0 1 0 1 0 1;
     0 1 1 0 0 1 1;
     0 0 0 1 1 1 1]


function find_G(H)
    all_idx = 1:size(H,2)
    I_idx = []
    for i in 1:size(H,2)
        col_sum = sum(H[:, i])
        if col_sum == 1
            push!(I_idx, i)
        end
    end
    A_idx = setdiff(all_idx, I_idx)
    A_T = H[:, A_idx]
    A = mod.(-1 * transpose(A_T), 2)
    I_G = Matrix{Int64}(I, size(A, 1), size(A, 1))
    G_sys = [I_G A]
    G_alp = Matrix{Int64}(undef, size(G_sys))
    G_alp[:, A_idx] = I_G
    G_alp[:, I_idx] = A
    return G_alp
end

CW3_DATA.Q9_1_a_ans_G = find_G(H)
# mod.(CW3_DATA.Q9_1_a_ans_G * transpose(H), 2)

4×7 Matrix{Int64}:
 1  1  1  0  0  0  0
 1  0  0  1  1  0  0
 0  1  0  1  0  1  0
 1  1  0  1  0  0  1

In [101]:
# Q9.1.b
# Q9_1_b_data_p :: Float64
# Q9_1_b_ans_p_err :: Union{Missing, Float64}

function decode_err(p)
    p_err = 1 - (1 - p)^7 - 7 * p * (1 - p)^6
    return p_err
end
p = CW3_DATA.Q9_1_b_data_p
CW3_DATA.Q9_1_b_ans_p_err = decode_err(p)

0.81369522728448

In [102]:
# Q9.1.c
# Q9_1_c_data_y_1 :: Vector{Int64}
# Q9_1_c_ans_i :: Union{Missing, Vector{Int64}}
# Q9_1_c_ans_ii :: Union{Missing, Vector{Int64}}
# Q9_1_c_ans_iii :: Union{Missing, Vector{Int64}}

H = [1 0 1 0 1 0 1;
     0 1 1 0 0 1 1;
     0 0 0 1 1 1 1]

function find_s(y, H)
    s = mod.(H * y, 2)   
    return s
end

function find_c(y, s, H)
    e = zeros(Int64, 7)
    for i in 1:7
        if s == H[:, i]
            e[i] = 1
        end
    end
    c = mod.(y - e, 2)
    return c
end

function find_m(c, G)
    I_idx = []
    for i in 1:size(G,2)
        col_sum = sum(G[:, i])
        if col_sum == 1
            push!(I_idx, i)
        end
    end
    m = c[I_idx]
    return m
end

y_1 = CW3_DATA.Q9_1_c_data_y_1
CW3_DATA.Q9_1_c_ans_i = find_s(y_1, H)
CW3_DATA.Q9_1_c_ans_ii = find_c(y_1, CW3_DATA.Q9_1_c_ans_i, H)
CW3_DATA.Q9_1_c_ans_iii = find_m(CW3_DATA.Q9_1_c_ans_ii, CW3_DATA.Q9_1_a_ans_G)
println("the syndrome vector s is ", CW3_DATA.Q9_1_c_ans_i)
println("the codeword c is ", CW3_DATA.Q9_1_c_ans_ii)
println("the message m is ", CW3_DATA.Q9_1_c_ans_iii)


the syndrome vector s is [0, 0, 1]
the codeword c is [1, 1, 1, 0, 0, 0, 0]
the message m is [1, 0, 0, 0]


In [103]:
# Q9.1.d
# Q9_1_d_data_y_2 :: Vector{Any}
# Q9_1_d_ans_i :: Union{Missing, Vector{Int64}}
# Q9_1_d_ans_ii :: Union{Missing, Vector{Int64}}
# Q9_1_d_ans_iii :: Union{Missing, Vector{Int64}}

function replace_symbol(y)
    for i in 1:length(y)
        if y[i] == "?"
            y[i] = 0
        end
    end
    return y
end

y_2 = replace_symbol(CW3_DATA.Q9_1_d_data_y_2)
CW3_DATA.Q9_1_d_ans_i = find_s(y_2, H)
CW3_DATA.Q9_1_d_ans_ii = find_c(y_2, CW3_DATA.Q9_1_d_ans_i, H)
CW3_DATA.Q9_1_d_ans_iii = find_m(CW3_DATA.Q9_1_d_ans_ii, CW3_DATA.Q9_1_a_ans_G)
println("the syndrome vector s is ", CW3_DATA.Q9_1_d_ans_i)
println("the codeword c is ", CW3_DATA.Q9_1_d_ans_ii)
println("the message m is ", CW3_DATA.Q9_1_d_ans_iii)

the syndrome vector s is [0, 0, 0]
the codeword c is [0, 0, 0, 0, 0, 0, 0]
the message m is [0, 0, 0, 0]


### 9.2

In [104]:
# Q9.2.a
# Q9_2_data_r :: Int64
# Q9_2_data_q :: Int64
# Q9_2_a_ans_H :: Union{Missing, Matrix{Int64}}

function generate_vec(r, q)
    non_zero_vec = []
    for i in 1:(q^r - 1)
        vec = digits(i, base=q, pad=r)
        if sum(vec) != 0
            push!(non_zero_vec, vec)
        end
    end
    return non_zero_vec  
end

function sort_H(vec)
    sum = 0
    for i in 1:length(vec)
        sum += vec[i] * 7^(i - 1)    
    end
    return sum
end 

function find_H(r, q)

    non_zero_vec = generate_vec(r, q)

    H = []
    for vec in non_zero_vec
        # Check if the vector is a scalar multiple of any vector already in H
        is_multiple = false
        for factor in 1:(q-1)
            if mod.(vec * factor, q) in H
                is_multiple = true
                break
            end
        end

        if !is_multiple
            push!(H, vec)
        end
    end

    H = hcat(H...)
    return sortslices(H, dims=2, by=sort_H)
    # return H
end

r = CW3_DATA.Q9_2_data_r
q = CW3_DATA.Q9_2_data_q

CW3_DATA.Q9_2_a_ans_H = find_H(r, q)

5×2801 Matrix{Int64}:
 1  0  1  2  3  4  5  6  0  1  2  3  4  …  2  3  4  5  6  0  1  2  3  4  5  6
 0  1  1  1  1  1  1  1  0  0  0  0  0     5  5  5  5  5  6  6  6  6  6  6  6
 0  0  0  0  0  0  0  0  1  1  1  1  1     6  6  6  6  6  6  6  6  6  6  6  6
 0  0  0  0  0  0  0  0  0  0  0  0  0     6  6  6  6  6  6  6  6  6  6  6  6
 0  0  0  0  0  0  0  0  0  0  0  0  0     1  1  1  1  1  1  1  1  1  1  1  1

In [105]:
# Q9.2.b
# Q9_2_b_ans_n :: Union{Missing, Int64}
# Q9_2_b_ans_k :: Union{Missing, Int64}
# Q9_2_b_ans_d :: Union{Missing, Int64}

function find_param(r, q)
    n = Int((q^r - 1) / (q - 1))
    k = Int(n - r)
    d = 3  # every two columns of H are linearly independent
    return n, k, d
end

r = CW3_DATA.Q9_2_data_r
q = CW3_DATA.Q9_2_data_q
CW3_DATA.Q9_2_b_ans_n, CW3_DATA.Q9_2_b_ans_k, CW3_DATA.Q9_2_b_ans_d = find_param(r, q)

(2801, 2796, 3)

In [106]:
# Q9.2.c
# Q9_2_c_ans_is_perfect_code :: Union{Missing,Bool}

function is_perfect(r, q, n)
    t = 1
    hamming_bound = 0

    for i in 0:t
        hamming_bound += binomial(n, i) * (q - 1)^i
    end

    if q^r == hamming_bound
        return true
    else
        return false
    end
end

r = CW3_DATA.Q9_2_data_r
q = CW3_DATA.Q9_2_data_q
n = CW3_DATA.Q9_2_b_ans_n
CW3_DATA.Q9_2_c_ans_is_perfect_code = is_perfect(r, q, n)

true

In [107]:
# Q9.2.d
# Q9_2_d_ans_G :: Union{Missing, Matrix{Int64}}

function find_G_2(H, q)
    all_idx = 1:size(H,2)
    I_idx = []
    for i in 1:size(H,2)
        col_sum = sum(H[:, i])
        if col_sum == 1
            push!(I_idx, i)
        end
    end
    A_idx = setdiff(all_idx, I_idx)
    A_T = H[:, A_idx]
    A = mod.(-1 * transpose(A_T), q)
    I_G = Matrix{Int64}(I, size(A, 1), size(A, 1))
    G_sys = [I_G A]
    G_alp = Matrix{Int64}(undef, size(G_sys))
    G_alp[:, A_idx] = I_G
    G_alp[:, I_idx] = A
    return G_alp
end

CW3_DATA.Q9_2_d_ans_G = find_G_2(CW3_DATA.Q9_2_a_ans_H, q)

# mod.(CW3_DATA.Q9_2_d_ans_G * transpose(CW3_DATA.Q9_2_a_ans_H), 7)

2796×2801 Matrix{Int64}:
 6  6  1  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 5  6  0  1  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 4  6  0  0  1  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 3  6  0  0  0  1  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 2  6  0  0  0  0  1  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 1  6  0  0  0  0  0  1  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 6  0  0  0  0  0  0  0  6  1  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 5  0  0  0  0  0  0  0  6  0  1  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 4  0  0  0  0  0  0  0  6  0  0  1  0     0  0  0  0  0  0  0  0  0  0  0  0
 3  0  0  0  0  0  0  0  6  0  0  0  1     0  0  0  0  0  0  0  0  0  0  0  0
 ⋮              ⋮              ⋮        ⋱     ⋮              ⋮              ⋮
 2  2  0  0  0  0  0  0  1  0  0  0  0     0  0  0  1  0  0  0  0  0  0  0  0
 1  2  0  0  0  0  0  0  1  0  0  0  0 

In [108]:
# Q9.2.e
# Q9_2_e_data_y_1 :: Vector{Int64}
# Q9_2_e_ans_i :: Union{Missing, Vector{Int64}}
# Q9_2_e_ans_ii :: Union{Missing, Vector{Int64}}
# Q9_2_e_ans_iii :: Union{Missing, Vector{Int64}}

function find_s_2(y, H, q)
    s = mod.(H * y, q) 
    return s
end

function find_c_2(y, s, H, q)
    e = zeros(Int64, size(H, 2))
    for i in 1:size(H, 2)
        if s == H[:, i]
            e[i] = 1
        end
    end
    c = mod.(y - e, q)
    return c
end

function find_m_2(c, G)
    I_idx = []
    for i in 1:size(G,2)
        col_sum = sum(G[:, i])
        if col_sum == 1
            push!(I_idx, i)
        end
    end
    m = c[I_idx]
    return m
end

y_1 = CW3_DATA.Q9_2_e_data_y_1
H = CW3_DATA.Q9_2_a_ans_H
CW3_DATA.Q9_2_e_ans_i = find_s_2(y_1, H, q)
CW3_DATA.Q9_2_e_ans_ii = find_c_2(y_1, CW3_DATA.Q9_2_e_ans_i, H, q)
CW3_DATA.Q9_2_e_ans_iii = find_m_2(CW3_DATA.Q9_2_e_ans_ii, CW3_DATA.Q9_2_d_ans_G)
println("the syndrome vector s is ", CW3_DATA.Q9_2_e_ans_i)
println("the codeword c is ", CW3_DATA.Q9_2_e_ans_ii)
println("the message m is ", CW3_DATA.Q9_2_e_ans_iii)

the syndrome vector s is [1, 4, 6, 0, 1]
the codeword c is [0, 3, 0, 1, 1, 1, 1, 1, 3, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 5, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1

, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,

, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,

, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [109]:
# Q9.2.f
# Q9_2_f_data_y_2 :: Vector{Any}
# Q9_2_f_ans_i :: Union{Missing, Vector{Int64}}
# Q9_2_f_ans_ii :: Union{Missing, Vector{Int64}}
# Q9_2_f_ans_iii :: Union{Missing, Vector{Int64}}

y_2 = replace_symbol(CW3_DATA.Q9_2_f_data_y_2)
CW3_DATA.Q9_2_f_ans_i = find_s_2(y_2, H, q)
CW3_DATA.Q9_2_f_ans_ii = find_c_2(y_2, CW3_DATA.Q9_2_f_ans_i, H, q)
CW3_DATA.Q9_2_f_ans_iii = find_m_2(CW3_DATA.Q9_2_f_ans_ii, CW3_DATA.Q9_2_d_ans_G)
println("the syndrome vector s is ", CW3_DATA.Q9_2_f_ans_i)
println("the codeword c is ", CW3_DATA.Q9_2_f_ans_ii)
println("the message m is ", CW3_DATA.Q9_2_f_ans_iii)

the syndrome vector s is [0, 5, 2, 1, 5]
the codeword c is [1, 3, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 4, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0

, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,

1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0

 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 

### 9.3

In [110]:
# Q9.3.a

using Primes
function is_primitive_root(p)
    
    phi = p - 1
    for a in 2:phi
        is_primitive = true
        for i in keys(Primes.factor(phi))
            order = div(phi, i)
            if powermod(a, order, p) == 1
                is_primitive = false
                break
            end
        end
        if is_primitive
            return a
        end
    end
end

p = CW3_DATA.Q9_3_data_p
CW3_DATA.Q9_3_a_ans_alpha = is_primitive_root(p)


2

In [111]:
# Q9.3.b
# Q9_3_data_n::Int
# Q9_3_data_k1::Int
# Q9_3_data_k2::Int
# Q9_3_data_p::Int


function RS_generator(n, k, p, alpha)
    G = zeros(Int64, k, n)
    for i in 1:k
        for j in 1:n
            G[i, j] = powermod(alpha, (i-1)*(j-1), p)
        end
    end
    
    H = zeros(Int64, n-k, n)
    for i in 1:(n-k)
        for j in 1:n
            H[i, j] = powermod(alpha, i*(j-1), p)
        end
    end
    return G, H
end

n = CW3_DATA.Q9_3_data_n
k1 = CW3_DATA.Q9_3_data_k1
k2 = CW3_DATA.Q9_3_data_k2
CW3_DATA.Q9_3_b_ans_generator, CW3_DATA.Q9_3_b_ans_parity = RS_generator(n, k1, p, CW3_DATA.Q9_3_a_ans_alpha)
display(CW3_DATA.Q9_3_b_ans_generator)
display(CW3_DATA.Q9_3_b_ans_parity)

5×10 Matrix{Int64}:
 1  1  1  1  1   1  1  1  1  1
 1  2  4  8  5  10  9  7  3  6
 1  4  5  9  3   1  4  5  9  3
 1  8  9  6  4  10  3  2  5  7
 1  5  3  4  9   1  5  3  4  9

5×10 Matrix{Int64}:
 1   2  4   8  5  10  9   7  3   6
 1   4  5   9  3   1  4   5  9   3
 1   8  9   6  4  10  3   2  5   7
 1   5  3   4  9   1  5   3  4   9
 1  10  1  10  1  10  1  10  1  10

In [112]:
# Q9.3.c

CW3_DATA.Q9_3_c_ans_generator, CW3_DATA.Q9_3_c_ans_parity = RS_generator(n, k2, p, CW3_DATA.Q9_3_a_ans_alpha)
display(CW3_DATA.Q9_3_c_ans_generator)
display(CW3_DATA.Q9_3_c_ans_parity)


2×10 Matrix{Int64}:
 1  1  1  1  1   1  1  1  1  1
 1  2  4  8  5  10  9  7  3  6

8×10 Matrix{Int64}:
 1   2  4   8  5  10  9   7  3   6
 1   4  5   9  3   1  4   5  9   3
 1   8  9   6  4  10  3   2  5   7
 1   5  3   4  9   1  5   3  4   9
 1  10  1  10  1  10  1  10  1  10
 1   9  4   3  5   1  9   4  3   5
 1   7  5   2  3  10  4   6  9   8
 1   3  9   5  4   1  3   9  5   4

In [113]:
# Q9.3.d

k3 = max(k1, k2)
CW3_DATA.Q9_3_d_ans_generator, CW3_DATA.Q9_3_d_ans_parity = RS_generator(n, k3, p, CW3_DATA.Q9_3_a_ans_alpha)
display(CW3_DATA.Q9_3_d_ans_generator)
display(CW3_DATA.Q9_3_d_ans_parity)


5×10 Matrix{Int64}:
 1  1  1  1  1   1  1  1  1  1
 1  2  4  8  5  10  9  7  3  6
 1  4  5  9  3   1  4  5  9  3
 1  8  9  6  4  10  3  2  5  7
 1  5  3  4  9   1  5  3  4  9

5×10 Matrix{Int64}:
 1   2  4   8  5  10  9   7  3   6
 1   4  5   9  3   1  4   5  9   3
 1   8  9   6  4  10  3   2  5   7
 1   5  3   4  9   1  5   3  4   9
 1  10  1  10  1  10  1  10  1  10

In [114]:
# Q9.3.e

k4 = min(k1, k2)
CW3_DATA.Q9_3_e_ans_generator, CW3_DATA.Q9_3_e_ans_parity = RS_generator(n, k4, p, CW3_DATA.Q9_3_a_ans_alpha)
display(CW3_DATA.Q9_3_e_ans_generator)
display(CW3_DATA.Q9_3_e_ans_parity)


2×10 Matrix{Int64}:
 1  1  1  1  1   1  1  1  1  1
 1  2  4  8  5  10  9  7  3  6

8×10 Matrix{Int64}:
 1   2  4   8  5  10  9   7  3   6
 1   4  5   9  3   1  4   5  9   3
 1   8  9   6  4  10  3   2  5   7
 1   5  3   4  9   1  5   3  4   9
 1  10  1  10  1  10  1  10  1  10
 1   9  4   3  5   1  9   4  3   5
 1   7  5   2  3  10  4   6  9   8
 1   3  9   5  4   1  3   9  5   4

In [115]:
# Q9.3.f

k5 = max(k1,k2)
CW3_DATA.Q9_3_f_ans_generator, CW3_DATA.Q9_3_f_ans_parity = RS_generator(n, k5, p, CW3_DATA.Q9_3_a_ans_alpha)
display(CW3_DATA.Q9_3_f_ans_generator)
display(CW3_DATA.Q9_3_f_ans_parity)

5×10 Matrix{Int64}:
 1  1  1  1  1   1  1  1  1  1
 1  2  4  8  5  10  9  7  3  6
 1  4  5  9  3   1  4  5  9  3
 1  8  9  6  4  10  3  2  5  7
 1  5  3  4  9   1  5  3  4  9

5×10 Matrix{Int64}:
 1   2  4   8  5  10  9   7  3   6
 1   4  5   9  3   1  4   5  9   3
 1   8  9   6  4  10  3   2  5   7
 1   5  3   4  9   1  5   3  4   9
 1  10  1  10  1  10  1  10  1  10

In [116]:
# Q9.3.g
k6 = k1 + k2
CW3_DATA.Q9_3_g_ans_generator, CW3_DATA.Q9_3_g_ans_parity = RS_generator(n, k6, p, CW3_DATA.Q9_3_a_ans_alpha)
display(CW3_DATA.Q9_3_g_ans_generator)
display(CW3_DATA.Q9_3_g_ans_parity)

7×10 Matrix{Int64}:
 1   1  1   1  1   1  1   1  1   1
 1   2  4   8  5  10  9   7  3   6
 1   4  5   9  3   1  4   5  9   3
 1   8  9   6  4  10  3   2  5   7
 1   5  3   4  9   1  5   3  4   9
 1  10  1  10  1  10  1  10  1  10
 1   9  4   3  5   1  9   4  3   5

3×10 Matrix{Int64}:
 1  2  4  8  5  10  9  7  3  6
 1  4  5  9  3   1  4  5  9  3
 1  8  9  6  4  10  3  2  5  7

### Data saving format for chapter 10:
* Use vectors to represent polynomials. If the polynomial is 1+x<sup>2</sup>+x<sup>3</sup>, then save it as [1 0 1 1]. No need to pad zero, i.e., the last element must be nonzero (except for the polynomial 0).
* Polynomial 0 is saved as [0], polynomial 1 is saved as [1].
* For syndrome vector s, error vector e and message m, save as a matrix where the number of row is 1.
* For S(x), L(x) and E(x), save as a matrix where the number of row is 1. Each element in this matrix represents the coefficient of the polynomial.

### 10.1


In [117]:
function Find_polynomial(a, gen)
    R_alpha = 0
    for i in 1:length(a)
        R_alpha += a[i]*gen^(i-1)
    end
    return R_alpha
end

function Create_Extension_Finite_Field(a, base, deg)
    # Create base field F2
    F_base = GF(base)
    # Create PolynomialRing based on this field
    R = PolynomialRing(F_base, "z")[1]
    # Create the irreducible polynomial based on coefficients vector
    f = R(a)
    # Create the extension finite field with q = base^deg
    F, generator = FiniteField(f, "z")
    return F, R, f, generator
end

# function Get_Generator_Matrix(R, f, a, n, k)
#     G_F = zeros(R, k, n)
#     for i in 1:k
#         for j in 1:n
#             G_F[i, j] = powermod(a, ((i-1)*(j-1)), f)
#         end
#     end
#     G = Matrix{Vector{Int64}}(undef, k, n)
#     for i in 1:k
#         for j in 1:n
#             G[i, j] = [Int(lift(c)) for c in coefficients(G_F[i, j])]
#         end
#     end
#     return G, G_F
# end
function Get_Generator_Matrix(R, F32, a, n, k)
        G_F = zeros(F32, k, n)
        for i in 1:k
            for j in 1:n
                G_F[i, j] = a^((i-1)*(j-1))
            end
        end
        G = Matrix{Vector{Int64}}(undef, k, n)
        for i in 1:k
            for j in 1:n
                G[i, j] = [Int(lift(c)) for c in coefficients(R(G_F[i, j]))]
            end
        end
        return G, G_F
end

# function Get_Parity_Check_Matrix(R, f, a, n, k)
#     H_F = zeros(R, n-k, n)
#     for i in 1:n-k
#         for j in 1:n
#             H_F[i, j] = powermod(a, (i*(j-1)), f)
#         end
#     end
#     H = Matrix{Vector{Int64}}(undef, n-k, n)
#     for i in 1:n-k
#         for j in 1:n
#             H[i, j] = [Int(lift(c)) for c in coefficients(H_F[i, j])]
#         end
#     end
#     return H, H_F
# end
function Get_Parity_Check_Matrix(R, F32, a, n, k)
    H_F = zeros(F32, n-k, n)
    for i in 1:n-k
        for j in 1:n
            H_F[i, j] = a^(i*(j-1))
        end
    end
    H = Matrix{Vector{Int64}}(undef, n-k, n)
    for i in 1:n-k
        for j in 1:n
            H[i, j] = [Int(lift(c)) for c in coefficients(R(H_F[i, j]))]
        end
    end
    return H, H_F
end


function Find_G_and_H(a, alpha, n, k)
    F32, R, f, z = Create_Extension_Finite_Field(a, 2, 5)
    # R_alpha = R(alpha)
    R_alpha = 0
    for i in 1:length(alpha)
        R_alpha += alpha[i]*z^(i-1)
    end
    # G, G_F = Get_Generator_Matrix(R, f, R_alpha, n, k)
    # H, H_F = Get_Parity_Check_Matrix(R, f, R_alpha, n, k)
    G, G_F = Get_Generator_Matrix(R, F32, R_alpha, n, k)
    H, H_F = Get_Parity_Check_Matrix(R, F32, R_alpha, n, k)
    H_t = zeros(F32, n-k, n)
    for i in 1:n-k
        for j in 1:n
            H_t[i, j] = Find_polynomial(H[i, j], z)
        end
    end
    G_t = zeros(F32, k, n)
    for i in 1:k
        for j in 1:n
            G_t[i, j] = Find_polynomial(G[i, j], z)
        end
    end
    return G, H, H_F, G_F, f, R_alpha, G_t, H_t
end



CW3_DATA.Q10_1_ans_G, CW3_DATA.Q10_1_ans_H, H_F, G_F, f, R_alpha, GT, HT = Find_G_and_H(CW3_DATA.Q10_data_polynomial, CW3_DATA.Q10_data_primitive_el, 31, 21)
# CW3_DATA.Q10_1_ans_H
check = G_F*transpose(H_F)
GT*transpose(HT)
# m, n = size(check)
# for i in 1:m
#     for j in 1:n
#         if check[i, j] != 0
#             println("error")
#         end
#     end
# end
# println("success")

# CW3_DATA.Q10_data_polynomial
# CW3_DATA.Q10_data_primitive_el
# CW3_DATA.Q10_1_ans_G



21×10 Matrix{fqPolyRepFieldElem}:
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 ⋮              ⋮           
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0

### 10.2


In [118]:
# function Find_s(a, H, y)
#     F32, R, f, z = Create_Extension_Finite_Field(a, 2, 5)
#     m_y, n_y = size(y)
#     y_F = zeros(R, m_y, n_y)
#     for i in 1:m_y
#         for j in 1:n_y
#             y_F[i, j] = R(y[i, j])
#         end
#     end
#     m_H, n_H = size(H)
#     H_F = zeros(R, m_H, n_H)
#     for i in 1:m_H
#         for j in 1:n_H
#             H_F[i, j] = R(H[i, j])
#         end
#     end
#     s_F = mod.(y_F*transpose(H_F), f)
#     s = Matrix{Vector{Int64}}(undef, m_y, m_H)
#     for i in 1:m_y
#         for j in 1:m_H
#             s[i, j] = [Int(lift(c)) for c in coefficients(s_F[i, j])] != [] ? [Int(lift(c)) for c in coefficients(s_F[i, j])] : [0]
#         end
#     end
#     return s
# end

function Find_s(a, H, y)
    F32, R, f, z = Create_Extension_Finite_Field(a, 2, 5)
    m_y, n_y = size(y)
    y_F = zeros(F32, m_y, n_y)
    for i in 1:m_y
        for j in 1:n_y
            y_F[i, j] = Find_polynomial(y[i, j], z)
        end
    end
    m_H, n_H = size(H)
    H_F = zeros(F32, m_H, n_H)
    for i in 1:m_H
        for j in 1:n_H
            H_F[i, j] = Find_polynomial(H[i, j], z)
        end
    end
    s_F = y_F*transpose(H_F)
    s = Matrix{Vector{Int64}}(undef, m_y, m_H)
    for i in 1:m_y
        for j in 1:m_H
            s[i, j] = [Int(lift(c)) for c in coefficients(R(s_F[i, j]))] != [] ? [Int(lift(c)) for c in coefficients(R(s_F[i, j]))] : [0]
        end
    end
    return s
end

# function Find_s_polynomial(a, H, y)
#     F32, R, f = Create_Extension_Finite_Field(a, 2, 5)
#     m_y, n_y = size(y)
#     y_F = zeros(R, m_y, n_y)
#     for i in 1:m_y
#         for j in 1:n_y
#             y_F[i, j] = R(y[i, j])
#         end
#     end
#     m_H, n_H = size(H)
#     H_F = zeros(R, m_H, n_H)
#     for i in 1:m_H
#         for j in 1:n_H
#             H_F[i, j] = R(H[i, j])
#         end
#     end
#     s_F = mod.(y_F*transpose(H_F), f) 
#     # construct the polynomial for x^j
#     x = zeros(Int64, m_H)
#     x[m_H] = 1
#     s_P_F = s_F[m_y, 1]*R(x)
#     for i in 2:m_H
#         x[i-1] = 0
#         x[i] = 1
#         s_P_F += s_F[m_y, i]*R(x)
#     end
#     s_P = []
#     push!(s_P, [Int(lift(c)) for c in coefficients(s_P_F)])
#     s = Matrix{Vector{Int64}}(undef, m_y, length(s_P))
#     s[m_y, 1:end] = s_P
#     return s
# end
    

CW3_DATA.Q10_2_ans_syndrome_vector = Find_s(CW3_DATA.Q10_data_polynomial, CW3_DATA.Q10_1_ans_H, CW3_DATA.Q10_2_data_y)
CW3_DATA.Q10_2_ans_syndrome_poly = Find_s(CW3_DATA.Q10_data_polynomial, CW3_DATA.Q10_1_ans_H, CW3_DATA.Q10_2_data_y)
# m, n = size(CW3_DATA.Q10_2_data_y)

1×10 Matrix{Vector{Int64}}:
 [0, 1, 1, 0, 1]  [1, 0, 0, 1, 1]  …  [1, 1, 0, 1]  [0, 1, 0, 1]

### 10.3


In [119]:
# function Find_L_and_E(a, s_p)
#     # Create base field F2
#     F_base = GF(2)
#     # Create PolynomialRing based on this field
#     Rz = PolynomialRing(F_base, "z")[1]
#     Rx = PolynomialRing(Rz, "x")[1]
#     # Create the irreducible polynomial based on coefficients vector
#     f = Rz(a)
#     # Create the extension finite field with q = base^deg
#     F_32 = FiniteField(f, "a")

#     m_s, n_s = size(s_p)
#     s_p_F = zeros(Rz, n_s)
#     for i in 1:m_s
#         for j in 1:n_s
#             s_p_F[j] = Rz(s_p[i, j])
#         end
#     end
#     S_x = Rx(s_p_F)
#     # Construct the ring polynomial for x^(d-1)
#     xd1 = zeros(Int64, n_s+1)
#     xd1[n_s+1] = 1
#     xd1_F = zeros(Rz, n_s+1)
#     for i in 1:n_s+1
#         xd1_F[i] = Rz(xd1[i])
#     end
#     X_dminus1 = Rx(xd1_F)
#     Ex_F, Lx_F, Bx_F = gcdx(S_x, X_dminus1)
#     Ex_coef_F = coefficients(Ex_F)
#     Ex = []
#     itr = 1
#     for element in Ex_coef_F
#         Ex_coef = []
#         coef = [Int(lift(c)) for c in coefficients(element)] != [] ? [Int(lift(c)) for c in coefficients(element)] : [0]
#         push!(Ex_coef, coef)
#         push!(Ex, Ex_coef)
#         itr += 1
#     end
#     Lx_coef_F = coefficients(Lx_F)
#     Lx = []
#     for element in Lx_coef_F
#         Lx_coef = []
#         coef = [Int(lift(c)) for c in coefficients(element)] != [] ? [Int(lift(c)) for c in coefficients(element)] : [0]
#         push!(Lx_coef, coef)
#         push!(Lx, Lx_coef)
#     end
#     # Convert to matrices
#     Ex_M = Matrix{Vector{Int64}}(undef, 1, length(Ex))
#     for i in 1:length(Ex)
#         Ex_M[1, i] = [Int64(x) for x in Ex[i][1]]
#     end
#     Lx_M = Matrix{Vector{Int64}}(undef, 1, length(Lx))
#     for i in 1:length(Lx)
#         Lx_M[1, i] = [Int64(x) for x in Lx[i][1]]
#     end
#     # return Lx, Ex
#     return Lx_M, Ex_M, Ex_F, Lx_F, S_x, X_dminus1, Bx_F
#     # println("ok")
# end

# CW3_DATA.Q10_3_ans_error_locator_poly, CW3_DATA.Q10_3_ans_error_evaluator_poly, EXF, LXF, Sx, Xd1, BXF = Find_L_and_E(CW3_DATA.Q10_data_polynomial, CW3_DATA.Q10_2_ans_syndrome_poly)
# # LXF
# CW3_DATA.Q10_3_ans_error_locator_poly
# LXF

function Extended_Euclidean_For_Polynomial(b_x, a_x, n, k, Rx)
    # Set up the initial conditions
    r_minus1_x = copy(a_x)
    r_0_x = copy(b_x)
    s_minus1_x = Rx(1)
    s_0_x = Rx(0)
    t_minus1_x = Rx(0)
    t_0_x = Rx(1)
    r_l_2_x = copy(r_minus1_x)
    r_l_1_x = copy(r_0_x)
    s_l_1_x = copy(s_0_x)
    s_l_2_x = copy(s_minus1_x)
    t_l_1_x = copy(t_0_x)
    t_l_2_x = copy(t_minus1_x)
    r_l_x = 0
    s_l_x = 0
    t_l_x = 0
    threshold = (n-k)/2-1
    deg_dif = 0
    # Start the iteration
    # while ((deg_dif >= 0))
    for i in 1:10
        if (degree(s_l_2_x) == threshold)
            break
        end
        q_l_x, r_l_x = divrem(r_l_2_x, r_l_1_x)
        s_l_x = s_l_2_x - q_l_x*s_l_1_x
        t_l_x = t_l_2_x - q_l_x*t_l_1_x
        # deg_dif = degree(r_l_x)-degree(r_l_1_x)
        deg_dif = degree(s_l_2_x) - threshold
        r_l_2_x = copy(r_l_1_x)
        r_l_1_x = copy(r_l_x)
        t_l_2_x = copy(t_l_1_x)
        t_l_1_x = copy(t_l_x)
        s_l_2_x = copy(s_l_1_x)
        s_l_1_x = copy(s_l_x)
    end
    L_x = t_l_2_x / coeff(t_l_2_x, 0)
    E_x = mod(L_x*b_x, a_x)
    return L_x, E_x
end




function Find_L_and_E(a, s_p)
    # Create base field F2
    F_base = GF(2)
    # Create PolynomialRing based on this field
    Rz = PolynomialRing(F_base, "z")[1]
    # Create the irreducible polynomial based on coefficients vector
    f = Rz(a)
    # Create the extension finite field with q = base^deg
    F_32, z = FiniteField(f, "z")
    Rx = PolynomialRing(F_32, "x")[1]

    m_s, n_s = size(s_p)
    s_p_F = zeros(F_32, n_s)
    for i in 1:m_s
        for j in 1:n_s
            s_p_F[j] = Find_polynomial(s_p[i, j], z)
        end
    end
    S_x = Rx(s_p_F)
    # S_x = Find_polynomial(s_p_F, x)
    # Construct the ring polynomial for x^(d-1)
    xd1_size = n_s+1
    xd1 = zeros(Int64, xd1_size)
    xd1[xd1_size] = 1
    xd1_F = zeros(F_32, xd1_size)
    for i in 1:xd1_size
        xd1_F[i] = Find_polynomial(xd1[i], z)
    end
    X_dminus1 = Rx(xd1_F)
    # X_dminus1 = Find_polynomial(xd1_F, x)
    Lx_F, Ex_F = Extended_Euclidean_For_Polynomial(S_x, X_dminus1, 31, 21, Rx)
    # Ex_F, Lx_F, Bx_F = gcdx(S_x, X_dminus1)
    Ex_coef_F = coefficients(Ex_F)
    Ex = []
    itr = 1
    for element in Ex_coef_F
        Ex_coef = []
        coef = [Int(lift(c)) for c in coefficients(Rz(element))] != [] ? [Int(lift(c)) for c in coefficients(Rz(element))] : [0]
        push!(Ex_coef, coef)
        push!(Ex, Ex_coef)
        itr += 1
    end
    Lx_coef_F = coefficients(Lx_F)
    Lx = []
    for element in Lx_coef_F
        Lx_coef = []
        coef = [Int(lift(c)) for c in coefficients(Rz(element))] != [] ? [Int(lift(c)) for c in coefficients(Rz(element))] : [0]
        push!(Lx_coef, coef)
        push!(Lx, Lx_coef)
    end
    # Convert to matrices
    Ex_M = Matrix{Vector{Int64}}(undef, 1, length(Ex))
    for i in 1:length(Ex)
        Ex_M[1, i] = [Int64(x) for x in Ex[i][1]]
    end
    Lx_M = Matrix{Vector{Int64}}(undef, 1, length(Lx))
    for i in 1:length(Lx)
        Lx_M[1, i] = [Int64(x) for x in Lx[i][1]]
    end
    # return Lx, Ex
    return Lx_M, Ex_M, Ex_F, Lx_F, S_x, X_dminus1, S_x, s_p_F
    # println("ok")
end

CW3_DATA.Q10_3_ans_error_locator_poly, CW3_DATA.Q10_3_ans_error_evaluator_poly, EXF, LXF, Sx, Xd1, SX, SPF = Find_L_and_E(CW3_DATA.Q10_data_polynomial, CW3_DATA.Q10_2_ans_syndrome_poly)
# LXF
# CW3_DATA.Q10_3_ans_error_locator_poly
# deg_dif
# mod(LXF*Sx, Xd1)
CW3_DATA.Q10_3_ans_error_locator_poly

LXF

(z^3 + z + 1)*x^5 + (z^4 + z + 1)*x^4 + (z^4 + z^3 + z^2 + z)*x^3 + (z^3 + z + 1)*x^2 + (z^4 + z)*x + 1

### 10.4


In [120]:
function Locator_x(Rz, f, x, Lx_vec)
    m, n = size(Lx_vec)
    Lx = Rz(0)
    for i in 1:n
        Lx = mod(Lx+mod(Rz(Lx_vec[i])*powermod(x, i-1, f), f), f)
    end
    return Lx
end

# function Find_Lx_gradient(F, a, Rz, f, x, Lx_vec)
#     n = length(F)
#     Lx_g = Rz(0)
#     for i in 1:n
#         # Lx_g = mod(Lx_g - mod(powermod(a, F[i], f)*mod(Locator_x(Rz, f, x, Lx_vec)*invmod(mod(1-mod(powermod(a, F[i], f)*x, f), f), f), f), f), f)
#         Lx_g = mod(Lx_g -powermod(a, F[i], f)*invmod(1-a^F[i]*x, f)*Locator_x(Rz, f, x, Lx_vec), f)
#     end
#     return Lx_g
# end

function Find_set_F(Lx, a_F, n, Rx, Rz, gen, f)
    F = []
    for i in 1:n
        # display(Rz(1)/a_F^((i-1)))
        # display(mod(inv(a_F^((i-1))), f))
        # display(compose(LxF, mod(inv(a_F^((i-1))), f)))
        # display( Locator_x(Rz, f, invmod(a_F^(i-1), f), Lx))
        if Locator_x(Rz, f, invmod(a_F^(i-1), f), Lx) == Rz(0)
            push!(F, i)
        end
    end
    return F
end


function Find_Error_Vector(a, Lx, Ex, alpha, n)
    # Create base field F2
    F_base = GF(2)
    # Create PolynomialRing based on this field
    Rz = PolynomialRing(F_base, "z")[1]
    Rx, gen = PolynomialRing(Rz, "x")
    # Create the irreducible polynomial based on coefficients vector
    f = Rz(a)
    # Create the extension finite field with q = base^deg
    F_32 = FiniteField(f, "z")
    # Get the primitive element
    a_F = Rz(alpha)
    F = Find_set_F(Lx, a_F, n, Rx, Rz, gen, f)
    e = zeros(Rz, n)
    for i in 1:length(F)
        # e[F[i]] = mod(-(mod(Locator_x(Rz, f, invmod(a_F^F[i], f), Ex)*invmod(Find_Lx_gradient(F, a_F, Rz, f, invmod(a_F^F[i], f), Lx), f), f)), f)
        e[F[i]] = mod(-Locator_x(Rz, f, invmod(a_F^F[i], f), Ex)*invmod(Locator_x(Rz, f, invmod(a_F^F[i], f), reshape([i*Lx[1, i+1] for i in 1:(size(Lx)[2]-1)], 1, size(Lx)[2]-1)), f), f)
        
    end
    # Find_Lx_gradient(F, a_F, Rz, f, invmod(a_F^F[1], f), Lx)
    # display(invmod(1-a_F^F[1]*x, f))
    # display(invmod(a_F^F[1], f))
    # for i in 1:length(F)
    #     display(invmod(1-a_F^F[i]*invmod(a_F^F[i], f), f))
    # end
    e_vec = Matrix{Vector{Int64}}(undef, 1, length(e))
    for i in 1:length(e)
        e_vec[1, i] = [Int(lift(c)) for c in coefficients(e[i])] != [] ? [Int(lift(c)) for c in coefficients(e[i])] : [0]
    end
    return e_vec, e
end

CW3_DATA.Q10_4_ans_error_vector, e_F = Find_Error_Vector(CW3_DATA.Q10_data_polynomial, CW3_DATA.Q10_3_ans_error_locator_poly, CW3_DATA.Q10_3_ans_error_evaluator_poly, CW3_DATA.Q10_data_primitive_el, 31)

println(CW3_DATA.Q10_4_ans_error_vector)


[[0] [0, 1, 1, 0, 1] [0, 0, 1, 1, 1] [0] [0] [0] [0] [0] [0, 0, 1, 1] [0] [0] [0] [0] [0] [0] [0] [0] [0] [0, 0, 1, 1, 1] [0] [0] [0] [0] [0] [0] [0, 0, 1] [0] [0] [0] [0] [0]]


### 10.5


In [121]:
function det_cofactor_FF(M, R)
  
    determinant = R(0)
    dim = size(M, 2)

    if dim == 2
        determinant = M[1, 1] * M[2, 2] - M[1, 2] * M[2, 1]
        return determinant
    end
    
    for idx in 1:dim
        M_minor = zeros(R, dim-1, dim-1)
        M_minor_new = zeros(R, dim-1, dim+2)
        M_new = zeros(R, dim-1, dim+3)
        M_new[1:(dim-1), 2:dim+1] = M[2:dim, 1:dim]
        M_minor_new[1:(dim-1), 1:idx] = M_new[1:(dim-1), 1:idx]
        M_minor_new[1:(dim-1), (idx+1):(dim+2)] = M_new[1:(dim-1), (idx+2):(dim+3)]
        M_minor[1:(dim-1), 1:(dim-1)] = M_minor_new[1:(dim-1), 2:(dim)]
  
        cofactor = (-1)^(1+idx) * det_cofactor_FF(M_minor, R)
      
        determinant += (M[1, idx] * cofactor)
    end
    
    return determinant
end

function inv_cofactor_FF(M, m, R, det_M)
    dim = size(M, 2)
    M_c = zeros(R, dim, dim)

    for i in 1:dim
        for j in 1:dim
            M_minor = zeros(R, dim-1, dim-1)
            M_minor_new = zeros(R, dim+2, dim+2)
            M_new = zeros(R, dim+3, dim+3)
            M_new[2:dim+1, 2:dim+1] = M[1:dim, 1:dim]
            M_minor_new[1:i, 1:j] = M_new[1:i, 1:j]
            M_minor_new[1:i, (j+1):(dim+2)] = M_new[1:i, (j+2):(dim+3)]
            M_minor_new[(i+1):(dim+2), 1:j] = M_new[(i+2):(dim+3), 1:j]
            M_minor_new[(i+1):(dim+2), (j+1):(dim+2)] = M_new[(i+2):(dim+3), (j+2):(dim+3)]
            M_minor[1:(dim-1), 1:(dim-1)] = M_minor_new[2:dim, 2:dim]
            M_c[i, j] = (-1)^(i+j) * det_cofactor_FF(M_minor, R)
        end
    end

    M_adj = transpose(M_c)
    M_inv = invmod(det_M, m) .* M_adj
    return mod.(M_inv, m)
end

function Find_message(a, e, y, G)
    F_base = GF(2)
    # Create PolynomialRing based on this field
    Rz = PolynomialRing(F_base, "z")[1]
    Rx, gen = PolynomialRing(Rz, "x")
    # Create the irreducible polynomial based on coefficients vector
    f = Rz(a)
    # Create the extension finite field with q = base^deg
    F_32 = FiniteField(f, "z")
    # Get the primitive element
    m_y, n_y = size(y)
    y_F = zeros(Rz, n_y)
    for j in 1:n_y
        y_F[j] = Rz(y[1, j])
    end
    c = mod.(y_F-e, f)
    c_vec = Matrix{Vector{Int64}}(undef, 1, length(c))
    for i in 1:length(c)
        c_vec[1, i] = [Int(lift(m)) for m in coefficients(c[i])] != [] ? [Int(lift(m)) for m in coefficients(c[i])] : [0]
    end
    k, n = size(G)
    m_vec = Matrix{Vector{Int64}}(undef, 1, k)
    m_vec[1, 1:k] = c_vec[1, 1:k]
    # det = det_cofactor_FF(G_F, Rz)
    # G_inv_F = inv_cofactor_FF(G, f, Rz, det)
    # G_new = G[1:21,1:21]
    # G_1 = MatrixSpace(F, 21, 21)()
    # G_inv_F = MatrixSpace(F, 21, 21)()

    # for i in 1:21
    #     for j in 1:21
    #         G_1[i, j] = vector_to_poly(G_new[i, j], z)
    #     end
    # end
    # G_inv_F = inv(G_1)
    # m = mod.(c*G_inv_F)
    return m_vec
end
CW3_DATA.Q10_5_ans_message = Find_message(CW3_DATA.Q10_data_polynomial, e_F, CW3_DATA.Q10_2_data_y, G_F)

1×21 Matrix{Vector{Int64}}:
 [1, 0, 0, 1]  [1, 1, 1, 0, 1]  …  [0, 0, 0, 1, 1]  [1, 1, 1, 1, 1]

### 10.6


In [122]:
function Find_n(m, base)
    coefficient = [sum(v[i] * 2^(i-1) for i in 1:length(v)) for v in m]
    n = reduce((acc, coef) -> acc + coef[1] * (Int(32))^(coef[2]-1), enumerate(coefficient), init=BigInt(0))
    return n
end

Find_n(CW3_DATA.Q10_5_ans_message, 32)
CW3_DATA.Q10_6_ans_n = Find_n(CW3_DATA.Q10_5_ans_message, 32)

114087525550162176

In [123]:
# save
jldopen("Jacky Jiang1860908StudentFile.jld2", "w") do file
    write(file, "CourseWork_3", CW3_DATA)
end